# Use 2 spaces for indentation
tab_spaces = 2
hard_tabs = false

# Function and control block formatting
fn_params_layout = "Vertical"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"

# Struct and enum formatting
struct_lit_single_line = false
struct_field_align_threshold = 0

# Import formatting
imports_layout = "HorizontalVertical"
imports_granularity = "Module"
group_imports = "StdExternalCrate"

# Comment formatting
comment_width = 100
wrap_comments = true

# Max line length and splitting preferences
max_width = 80
use_small_heuristics = "Max"
chain_width = 80
array_width = 80
attr_fn_like_width = 80
struct_lit_width = 80
struct_variant_width = 80

# Chain splitting preferences
match_block_trailing_comma = true
trailing_comma = "Vertical"